/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Sun Mar 23 20:52:25 2014. */

#include "heartbeat.pb.h"



const pb_field_t Heartbeat_fields[3] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, Heartbeat, millis, millis, 0),
    PB_FIELD2(  2, INT32   , REQUIRED, STATIC  , OTHER, Heartbeat, ticks, millis, 0),
    PB_LAST_FIELD
};


