/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.6 at Mon Mar 24 22:54:50 2014. */

#ifndef _PB_HEARTBEAT_PB_H_
#define _PB_HEARTBEAT_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Heartbeat_Message {
    Heartbeat_Message_Id = 1
} Heartbeat_Message;

/* Struct definitions */
typedef struct _Heartbeat {
    int32_t millis;
    int32_t ticks;
} Heartbeat;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define Heartbeat_millis_tag                     1
#define Heartbeat_ticks_tag                      2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Heartbeat_fields[3];

/* Maximum encoded size of messages (where known) */
#define Heartbeat_size                           22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
