/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Mon Mar 24 22:54:50 2014. */

#include "movement.pb.h"



const pb_field_t Movement_fields[4] = {
    PB_FIELD2(  1, SINT32  , REQUIRED, STATIC  , FIRST, Movement, power, power, 0),
    PB_FIELD2(  2, SINT32  , REQUIRED, STATIC  , OTHER, Movement, direction, power, 0),
    PB_FIELD2(  3, INT32   , REQUIRED, STATIC  , OTHER, Movement, duration, direction, 0),
    PB_LAST_FIELD
};


