/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Sun Mar 23 20:52:25 2014. */

#include "movement.pb.h"



const pb_field_t Movement_fields[3] = {
    PB_FIELD2(  1, SINT32  , REPEATED, CALLBACK, FIRST, Movement, power, power, 0),
    PB_FIELD2(  2, INT32   , REQUIRED, STATIC  , OTHER, Movement, duration, power, 0),
    PB_LAST_FIELD
};


