cc_binary(
  name = 'cmdmsg',
  srcs = ['CmdMessenger.cpp',
          'host-serial.cpp',
          'main.cpp'],
  extra_cppflags = ['-Wno-conversion-null',
                    '-Wno-unused-value',
                    '-Wno-format-nonliteral',
                    '-Wno-type-limits']
)

